# Generated by Django 3.0.6 on 2020-05-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjuge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=200)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Pessoa')),
            ],
        ),
    ]
